workflows:
  ios:
    name: Build iOS
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build the app for iOS
        script: npx react-native run-ios 
      - name: Archive the app
        script: xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp archive -archivePath build/ios/YourApp.xcarchive
