workflows:
  ios:
    name: Build iOS
    max_build_duration: 120 # Optional: Thời gian tối đa cho mỗi build
    steps:
      - checkout # Lấy mã nguồn từ repository
      - install:
          cocoapods: true # Cài đặt các pods nếu có
      - run:
          name: Build the app for iOS
          command: |
            npx react-native run-ios --configuration Release
      - upload-artifact:
          path: build/ios/Release-iphoneos/*.ipa # Đường dẫn đến file IPA được tạo ra sau build
